[package]
edition = "2021"
name = "worker"
version = "0.1.0"

[dependencies]
ariadne = { version = "0.4", default-features = false }
bincode = "1"
bytemuck = "1"
comemo = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }
protocol = { path = "../protocol" }
thiserror = "1"
time = "0.3"
ttf-parser = "0.21"
typst = "0.11"
typst-render = "0.11"

# downloading packages
zune-inflate = { version = "0.2", default-features = false, features = [
	"gzip",
	"std",
] }
tar = "0.4"
ureq = "2"

[build-dependencies]
cargo_metadata = "0.18"
