services:
  typst-bot:
    build: 
      dockerfile: Dockerfile
      target: prod
    environment:
      - CACHE_DIRECTORY=/bot/cache
    env_file: .env
    container_name: typst-bot
    restart: always